### ISSUE TITLE
Guide for JAVA ?

### ISSUE THREAD

**Issue by LassassinX** [kcrimi/ToolTipDialog#14]
Many of us are still programming in Java on android.
It would be super helpful if you could Make a guide on JAVA.
I'm totally lost as to how to implement this.

**Comment by kcrimi** [comment]
Hey @LassassinX I'm not quite sure which part is tripping you up. Most of the syntax will be the same except instead of `ToolTipDialog(this, this)` you would add the java command `new` to make `new ToolTipDialog(this, this)`. Let me know if there's something else that you're getting tripped up by

**Comment by LassassinX** [comment]
Hello, sorry for not being elaborate earlier. I keep instantiating a new ToolTipDialog like ToolTipDialog td = new ToolTipDialog(this, this, R.styles.AppTheme), as it takes 3 arguments. However, after setting the title and submessage and stuff, when i call .show(), it gives me an exception saying that the width and height must be greater than 0. Any idea what im doing wrong ?

**Comment by kcrimi** [comment]
Ask ok. My guess is you're probably trying to create it inside a very early lifecycle event like onCreate() rather than on a click event. This will cause problems since the view is not drawn yet so every view still has height and width of 0.

Try out the solution in the FAQ 
https://github.com/kcrimi/ToolTipDialog#faq
If that doesn't work, it'll help if you paste in your code.

**Comment by kcrimi** [comment]
@LassassinX have you had any luck with the view tree observer solution?

**Comment by LassassinX** [comment]
I haven't tried it yet, I will try it out soon and let you know asap

**Comment by kcrimi** [comment]
Closing this issue. We can reopen it if OP comes back with more info
