### ISSUE TITLE
Wasted few hours trying to import it propery.

### ISSUE THREAD

**Issue by fantasticrahulrai** [kcrimi/ToolTipDialog#2]
Dude, this library wasted my few hours bcz even after importing the library poperly using jCenter, bintray, jitpack. 

I Was unable to import the classes in the activity. Plz check.

**Comment by kcrimi** [comment]
Hey Rahul, sorry to hear it's not working for you. Does the sample app compile for you? That uses the jcenter version of the library rather than the local so if that works, it should work in your project as well.

I'm currently traveling so I won't be able to investigate for a few days but feel free to leave more info that you may find in the meantime

**Comment by fantasticrahulrai** [comment]
Hey dear, thanks a lot for such a quick response. No I haven't complied the sample app. Will try to do that and let you know. I would just recommend to make the library easily importable using jitpack.  Happy journey.

**Comment by kcrimi** [comment]
Hi, I wanted to check if you had a chance to try the sample project? 

I can consider also publishing through jitpack as well though no urgent plans to do so yet.

**Comment by kcrimi** [comment]
I've updated the README to specify the requirement of adding the jcenter() repository. Hopefully you've been able to get this sorted out in the meantime.

I'm closing the issue since the importing from jcenter appears to be working
